### ISSUE TITLE
[build] AioReadTimeoutError when downloading build artifacts

### ISSUE THREAD

**Issue by tsibley** [nextstrain/cli#121]
@trvrb [reported](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1617652176019000) encountering an error when trying to download build artifacts using `nextstrain build --aws-batch --attach …`:

```
aiobotocore.response.AioReadTimeoutError: Read timeout on endpoint URL
```

<details>
<summary>Full error message</summary>

```
unzipping: /Users/trvrb/Documents/src/ncov/results/aligned_gisaid.fasta
Traceback (most recent call last):
  File "/Users/trvrb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/aiobotocore/response.py", line 50, in read
    chunk = await self.__wrapped__.read(amt if amt is not None else -1)
  File "/Users/trvrb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/aiohttp/streams.py", line 370, in read
    block = await self.readany()
  File "/Users/trvrb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/aiohttp/streams.py", line 392, in readany
    await self._wait("readany")
  File "/Users/trvrb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/aiohttp/streams.py", line 306, in _wait
    await waiter
aiohttp.client_exceptions.ServerTimeoutError: Timeout on reading data from socket
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/trvrb/.pyenv/versions/3.6.5/bin/nextstrain", line 11, in <module>
    sys.exit(main())
  File "/Users/trvrb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/nextstrain/cli/__main__.py", line 10, in main
    return cli.run( argv[1:] )
  ...
  File "/Users/trvrb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/fsspec/asyn.py", line 55, in f
    result[0] = await future
  File "/Users/trvrb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/aiobotocore/response.py", line 53, in read
    error=e)
aiobotocore.response.AioReadTimeoutError: Read timeout on endpoint URL: "https://nextstrain-jobs.s3.amazonaws.com/2899b2dc-dcbb-4335-a92b-6306d98f3792.zip"
```

</details>

On the face of it, this _seems_ to me to be a network-related issue, not an issue with any software we control, but if we can learn more about it we might be able to do something better. Trevor noted that

> I had assumed it was just my home internet when it happened last night, but surprised that it failed on the Hutch internet [today]. And I don't think I've encountered this before and then twice in 24 hours.

The default timeouts seem quite long enough (~5 min) and seem to apply to connections where data is not being received. We might need to tweak a default timeout, but I wouldn't expect this to be the case if data is flowing. There are a number of timeout-related isssues on GitHub for aiohttp, which is the underlying library used by one of our deps, but it's not clear without further digging which might apply here, if any. 

Because file size might come into play here, I grabbed the info for the file which was being downloaded:

```
>>> import fsspec, zipfile
>>> f = fsspec.open("s3://nextstrain-jobs/2899b2dc-dcbb-4335-a92b-6306d98f3792.zip")
>>> z = zipfile.ZipFile(f.open())
>>> z.getinfo("results/aligned_gisaid.fasta")
<ZipInfo filename='results/aligned_gisaid.fasta' compress_type=deflate filemode='-rw-r--r--' file_size=28742499056 compress_size=3699095261>
```

I think next steps are to investigate further into how aiohttp and aiobotocore handle timeouts, in particular the two implicated in the full error message stacktrace above. Closely reading the existing GH issues as well as the source code will be necessary here. Hopefully that will lead to a hypothesis about why this could be occurring, which we can use to try to reliably reproduce and test it.

**Comment by jameshadfield** [comment]
In case this helps someone, I am able to avoid these timeouts (in most cases) by making sure the computer doesn't sleep during download (which can often take hours for the nCoV workflow). On MacOS this can be done via
```
caffeinate -s nextstrain build --aws-batch --download ...
```
