### ISSUE TITLE
BUG: Uncaught `ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory` via mamba/Ubuntu

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/cli#203]
### Current Behavior
When using `nextstrain login` I get the following error on a `nextstrain` installation via miniconda/mamba on an AWS VM:
```
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
```

### Expected behavior
Installing from conda works, any dependencies are installed and specified, including libssl if it's not present.

### How to reproduce
Hard to say, depends on machine setup, mine was pretty straightforward, just download miniconda, mamba, then install according to our docs

### Possible solution
Specify libssl as run dependency in conda?

### Your environment: if browsing Nextstrain online
Ubuntu 22.04

### Additional context
```bash
(nextstrain) ubuntu@ip-172-31-15-175:~/ncov-simple-daily-builds$ nextstrain login
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/nextstrain/bin/nextstrain", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/nextstrain/cli/__main__.py", line 19, in main
    return cli.run( argv[1:] )
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/nextstrain/cli/__init__.py", line 33, in run
    return opts.__command__.run(opts)
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/nextstrain/cli/command/login.py", line 66, in run
    user = current_user()
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/nextstrain/cli/authn.py", line 126, in current_user
    session.verify_tokens(**tokens)
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/nextstrain/cli/aws/cognito/__init__.py", line 232, in verify_tokens
    self._verify_token(id_token, "id")
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/nextstrain/cli/aws/cognito/__init__.py", line 246, in _verify_token
    jwk = self.jwks.get_signing_key_from_jwt(token)
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/jwt/jwks_client.py", line 59, in get_signing_key_from_jwt
    return self.get_signing_key(header.get("kid"))
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/jwt/jwks_client.py", line 41, in get_signing_key
    signing_keys = self.get_signing_keys()
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/jwt/jwks_client.py", line 28, in get_signing_keys
    jwk_set = self.get_jwk_set()
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/jwt/jwks_client.py", line 25, in get_jwk_set
    return PyJWKSet.from_dict(data)
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/jwt/api_jwk.py", line 92, in from_dict
    return PyJWKSet(keys)
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/jwt/api_jwk.py", line 87, in __init__
    self.keys.append(PyJWK(key))
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/jwt/api_jwk.py", line 52, in __init__
    self.key = self.Algorithm.from_jwk(self._jwk_data)
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/jwt/algorithms.py", line 368, in from_jwk
    return numbers.public_key()
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 409, in public_key
    from cryptography.hazmat.backends.openssl.backend import (
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 63, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/home/ubuntu/miniconda3/envs/nextstrain/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by corneliusroemer** [comment]
We may be in trouble here, looks like libssl3 is used in Ubuntu :o 
https://askubuntu.com/a/1412746/686407

**Comment by tsibley** [comment]
Ah, it shouldn't matter what the base OS uses, since whatever is required should be installed by Conda. Conda often installs different OpenSSL versions separately from the base OS.

I'm not sure why Conda is not doing the right thing here, but this is AFAICT firmly a Conda issue (either bug or bad recipe), not something we can fix from this repo.

**Comment by victorlin** [comment]
This looks like a duplicate of #184 with a slightly different message

**Comment by corneliusroemer** [comment]
This is notably not on mac as #184 but Ubuntu 22.04

What's the right place to raise this? Since we maintain the conda package, we should also fix it so I'd say we should keep this open as a conda distribution bug?

I installed everything cleanly and still get this error on Ubuntu 22.04 so this could be encountered by more people in the future?

**Comment by tsibley** [comment]
@corneliusroemer shared a repro in Slack, which I copied below.

On Ubuntu 22.04, run:

```
mkdir -p ~/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm -rf ~/miniconda3/miniconda.sh
~/miniconda3/bin/conda init bash
```

Log out and back in so that conda activation works.

Install Mamba.

```
conda install mamba -n base -c conda-forge --yes
```

Install Nextstrain environment

```
mamba create -n nextstrain \
    -c conda-forge -c bioconda \
    nextstrain-cli augur auspice nextalign nextclade snakemake git epiweeks pangolin pangolearn \
    --yes
```

**Comment by tsibley** [comment]
@corneliusroemer We can track this as part of #184. I'd forgotten we had that open still. I'm not sure that this is ultimately an issue with the Bioconda bits we maintain (e.g. I think the fix may be upstream of our purview), but it of course certainly affects our distributions and we can try to help debug/fix it. Having it occur on Linux will be helpful for me to be able to debug it, so I'll see if I can indeed repro.
