### ISSUE TITLE
`OSError: [Errno 40] Your request was too big` on stock RSV repo build via aws-batch

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/cli#271]
### Current Behavior
When trying to run the nextstrain/rsv workflow using `nextstrain build --aws-batch ...` I get an error: `OSError: [Errno 40] Your request was too big.`

### Expected behavior
It works, I don't get such an error, or at least cli can recover and advise me on how to workaround the issue.

### How to reproduce
Steps to reproduce the current behavior:
1. `gh repo clone nextstrain/rsv`
2. Run:
 ```
 nextstrain build \         
    --aws-batch \
    --detach \
    --no-download \
    --cpus 16 \
    --memory 64gib \
    --exec env \
    . \
      snakemake \                  
        --configfiles config/configfile.yaml  \                                 
        --printshellcmds
```
3. See error

### Your environment: if running Nextstrain locally
 - Operating system: macOS 13.3.1 on M1
 - shell: zsh
 - version: `nextstrain.cli 6.2.1`
 
### Full logs
<details>

 ```
 nextstrain build \         
      --aws-batch \
      --detach \
      --no-download \
      --cpus 16 \
      --memory 64gib \
      --exec env \
      . \
        snakemake \                  
          --configfiles config/configfile.yaml  \                                 
          --printshellcmds
  Nextstrain Run ID: b1df3dba-e7b9-4336-8eff-754cd2727e17
  Uploading /Users/corneliusromer/code/rsv to S3
  zipping: /Users/corneliusromer/code/rsv
  zipping: /Users/corneliusromer/code/rsv/bin
  zipping: /Users/corneliusromer/code/rsv/bin/notify-on-deploy
  zipping: /Users/corneliusromer/code/rsv/bin/set-branch-ingest-config
  zipping: /Users/corneliusromer/code/rsv/bin/notify-on-error
  zipping: /Users/corneliusromer/code/rsv/bin/write-envdir
  zipping: /Users/corneliusromer/code/rsv/bin/notify-on-start
  zipping: /Users/corneliusromer/code/rsv/bin/notify-on-success
  zipping: /Users/corneliusromer/code/rsv/config
  zipping: /Users/corneliusromer/code/rsv/config/clades_genome_a.tsv
  zipping: /Users/corneliusromer/code/rsv/config/clades_genome_b.tsv
  zipping: /Users/corneliusromer/code/rsv/config/color_orderings.tsv
  zipping: /Users/corneliusromer/code/rsv/config/clades_G_b.tsv
  zipping: /Users/corneliusromer/code/rsv/config/areference.gbk
  zipping: /Users/corneliusromer/code/rsv/config/configfile.yaml
  zipping: /Users/corneliusromer/code/rsv/config/clades_G_a.tsv
  zipping: /Users/corneliusromer/code/rsv/config/description.md
  zipping: /Users/corneliusromer/code/rsv/config/outliers.txt
  zipping: /Users/corneliusromer/code/rsv/config/breference.gbk
  zipping: /Users/corneliusromer/code/rsv/config/areference.fasta
  zipping: /Users/corneliusromer/code/rsv/config/color_schemes.tsv
  zipping: /Users/corneliusromer/code/rsv/config/nextstrain_automation.yaml
  zipping: /Users/corneliusromer/code/rsv/config/breference.fasta
  zipping: /Users/corneliusromer/code/rsv/config/auspice_config.json
  zipping: /Users/corneliusromer/code/rsv/ingest
  zipping: /Users/corneliusromer/code/rsv/ingest/bin
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/notify-on-job-start
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/transform-authors
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/transform-field-names
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/upload-to-s3
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/gene-coverage.py
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/transform-date-fields
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/sort.py
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/csv-to-ndjson.py
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/transform-genbank-location
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/ndjson-to-tsv-and-fasta
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/notify-slack
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/merge-user-metadata
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/notify-on-job-fail
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/notify-on-record-change
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/apply-geolocation-rules
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/join-metadata-and-clades.py
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/metadata_dedup.py
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/fasta-to-ndjson
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/sha256sum
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/s3-object-exists
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/sequencesandmetadata.py
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/transform-string-fields
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/cloudfront-invalidate
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/genbank-url
  zipping: /Users/corneliusromer/code/rsv/ingest/bin/transform-strain-names
  zipping: /Users/corneliusromer/code/rsv/ingest/config
  zipping: /Users/corneliusromer/code/rsv/ingest/config/b_1_reference.fasta
  zipping: /Users/corneliusromer/code/rsv/ingest/config/config.yaml
  zipping: /Users/corneliusromer/code/rsv/ingest/config/a_1_reference.fasta
  zipping: /Users/corneliusromer/code/rsv/ingest/config/a_3_reference.fasta
  zipping: /Users/corneliusromer/code/rsv/ingest/config/b_2_reference.fasta
  zipping: /Users/corneliusromer/code/rsv/ingest/config/b_3_reference.fasta
  zipping: /Users/corneliusromer/code/rsv/ingest/config/a_2_reference.fasta
  zipping: /Users/corneliusromer/code/rsv/ingest/config/optional.yaml
  zipping: /Users/corneliusromer/code/rsv/ingest/source-data
  zipping: /Users/corneliusromer/code/rsv/ingest/source-data/geolocation-rules.tsv
  zipping: /Users/corneliusromer/code/rsv/ingest/source-data/annotations.tsv
  zipping: /Users/corneliusromer/code/rsv/ingest/Snakefile
  zipping: /Users/corneliusromer/code/rsv/ingest/workflow
  zipping: /Users/corneliusromer/code/rsv/ingest/workflow/envs
  zipping: /Users/corneliusromer/code/rsv/ingest/workflow/envs/nextstrain.yaml
  zipping: /Users/corneliusromer/code/rsv/ingest/workflow/snakemake_rules
  zipping: /Users/corneliusromer/code/rsv/ingest/workflow/snakemake_rules/fetch_sequences.smk
  zipping: /Users/corneliusromer/code/rsv/ingest/workflow/snakemake_rules/upload.smk
  zipping: /Users/corneliusromer/code/rsv/ingest/workflow/snakemake_rules/sort.smk
  zipping: /Users/corneliusromer/code/rsv/ingest/workflow/snakemake_rules/transform.smk
  zipping: /Users/corneliusromer/code/rsv/README.md
  zipping: /Users/corneliusromer/code/rsv/env.d
  zipping: /Users/corneliusromer/code/rsv/Snakefile
  zipping: /Users/corneliusromer/code/rsv/logs
  zipping: /Users/corneliusromer/code/rsv/logs/traits_rsv_rsv.txt
  zipping: /Users/corneliusromer/code/rsv/workflow
  zipping: /Users/corneliusromer/code/rsv/workflow/envs
  zipping: /Users/corneliusromer/code/rsv/workflow/envs/nextstrain.yaml
  zipping: /Users/corneliusromer/code/rsv/workflow/snakemake_rules
  zipping: /Users/corneliusromer/code/rsv/workflow/snakemake_rules/glycosylation.smk
  zipping: /Users/corneliusromer/code/rsv/workflow/snakemake_rules/core.smk
  zipping: /Users/corneliusromer/code/rsv/workflow/snakemake_rules/clades.smk
  zipping: /Users/corneliusromer/code/rsv/workflow/snakemake_rules/export.smk
  zipping: /Users/corneliusromer/code/rsv/workflow/snakemake_rules/nextstrain_automation.smk
  zipping: /Users/corneliusromer/code/rsv/workflow/snakemake_rules/download.smk
  zipping: /Users/corneliusromer/code/rsv/scripts
  zipping: /Users/corneliusromer/code/rsv/scripts/clade_names.py
  zipping: /Users/corneliusromer/code/rsv/scripts/newreference.py
  zipping: /Users/corneliusromer/code/rsv/scripts/glycosylation.py
  zipping: /Users/corneliusromer/code/rsv/scripts/cut.py
  zipping: /Users/corneliusromer/code/rsv/scripts/align_for_tree.py
  zipping: /Users/corneliusromer/code/rsv/scripts/assign-colors.py
  zipping: /Users/corneliusromer/code/rsv/scripts/set_final_strain_name.py
  zipping: /Users/corneliusromer/code/rsv/scripts/wrangle_metadata.py
  zipping: /Users/corneliusromer/code/rsv/scripts/metadatadedup.py
  zipping: /Users/corneliusromer/code/rsv/.github
  zipping: /Users/corneliusromer/code/rsv/.github/workflows
  zipping: /Users/corneliusromer/code/rsv/.github/workflows/fetch-and-ingest.yaml
  zipping: /Users/corneliusromer/code/rsv/.github/workflows/rebuild.yaml
  /opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/botocore/utils.py:1720: FutureWarning: The S3RegionRedirector class has been deprecated for a new internal replacement. A future version of botocore may remove this class.
    warnings.warn(
  Traceback (most recent call last):
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/s3fs/core.py", line 112, in _error_wrapper
      return await func(*args, **kwargs)
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/aiobotocore/client.py", line 358, in _make_api_call
      raise error_class(parsed_response, operation_name)
  botocore.exceptions.ClientError: An error occurred (MaxMessageLengthExceeded) when calling the PutObject operation: Your request was too big.
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/bin/nextstrain", line 8, in <module>
      sys.exit(main())
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/nextstrain/cli/__main__.py", line 19, in main
      return cli.run( argv[1:] )
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/nextstrain/cli/__init__.py", line 36, in run
      return opts.__command__.run(opts)
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/nextstrain/cli/command/build.py", line 195, in run
      return runner.run(opts, working_volume = opts.build, cpus = opts.cpus, memory = opts.memory)
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/nextstrain/cli/runner/__init__.py", line 232, in run
      return opts.__runner__.run(opts, argv, working_volume = working_volume, extra_env = extra_env, cpus = cpus, memory = memory)
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/nextstrain/cli/runner/aws_batch/__init__.py", line 129, in run
      remote_workdir = s3.upload_workdir(local_workdir, bucket, run_id)
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/nextstrain/cli/runner/aws_batch/s3.py", line 68, in upload_workdir
      with fsspec.open(object_url(remote_workdir), "wb", auto_mkdir = False) as remote_file:
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/fsspec/core.py", line 121, in __exit__
      self.close()
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/fsspec/core.py", line 141, in close
      f.close()
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/fsspec/spec.py", line 1789, in close
      self.flush(force=True)
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/fsspec/spec.py", line 1660, in flush
      if self._upload_chunk(final=force) is not False:
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/s3fs/core.py", line 2215, in _upload_chunk
      self.commit()
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/s3fs/core.py", line 2230, in commit
      write_result = self._call_s3(
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/s3fs/core.py", line 2082, in _call_s3
      return self.fs.call_s3(method, self.s3_additional_kwargs, *kwarglist, **kwargs)
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/fsspec/asyn.py", line 115, in wrapper
      return sync(self.loop, func, *args, **kwargs)
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/fsspec/asyn.py", line 100, in sync
      raise return_result
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/fsspec/asyn.py", line 55, in _runner
      result[0] = await coro
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/s3fs/core.py", line 347, in _call_s3
      return await _error_wrapper(
    File "/opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/lib/python3.10/site-packages/s3fs/core.py", line 139, in _error_wrapper
      raise err
  OSError: [Errno 40] Your request was too big.
  ```
</details>

**Comment by tsibley** [comment]
@corneliusroemer What's the output of `nextstrain version --verbose`?

**Comment by tsibley** [comment]
Hm. This is coming from inside the aiobotocore client used by fsspec/s3fs. My first guess (probably wrong) is that you have an incompatible combination of s3fs and aiobotocore in whatever environment `nextstrain` itself is running.

**Comment by corneliusroemer** [comment]
```
$ nextstrain version --verbose
nextstrain.cli 6.2.1

Python
  /opt/homebrew/Caskroom/miniforge/base/envs/nextstrain/bin/python3.10
  3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:31:57) [Clang 14.0.6 ]

Runners
  docker 
    nextstrain/base:build-20230411T103027Z (bb05df2db0ce, 2023-04-11 13:38:55 +0200 CEST)
    augur 21.1.0
    auspice v2.45.2
    fauna e3ed8e1
    sacra not present

  conda 
    nextstrain-base 20230407T195218Z (h0dc7051_1_locked, nextstrain)
    augur 21.1.0
    auspice 2.45.1

  singularity 
    docker://nextstrain/base (not present)

  ambient (default)
    augur 21.1.0
    auspice 2.45.1

  aws-batch 
    unknown
```

**Comment by tsibley** [comment]
I ask because I wonder if https://github.com/bioconda/bioconda-recipes/pull/39711 is implicated. Though not certain if the expectation would be that you have a version of `nextstrain-cli` from Bioconda _before_ or _after_ that…

**Comment by tsibley** [comment]
This seems worth digging into, but I'd love if someone else in @nextstrain/core could pick it up.
