### ISSUE TITLE
Python user site directory leaks into Conda runtime

### ISSUE THREAD

**Issue by RubenHaag** [nextstrain/cli#309]
### Current Behavior
```bash
$ nextstrain setup --set-default conda 

Setting up conda…
Removing existing directory /home/username/.nextstrain/runtimes/conda/micromamba to start fresh…
Requesting Micromamba from https://api.anaconda.org/download/conda-forge/micromamba/1.1.0/linux-64/micromamba-1.1.0-1.tar.bz2…
Downloading and extracting Micromamba to /home/username/.nextstrain/runtimes/conda/micromamba…
Removing existing directory /home/username/.nextstrain/runtimes/conda/env to start fresh…
Installing Conda packages into /home/username/.nextstrain/runtimes/conda/env…
  - nextstrain-base

...snip...

Checking setup…
Traceback (most recent call last):
  File "/home/username/.nextstrain/runtimes/conda/env/bin/augur", line 6, in <module>
    from augur.__main__ import main
  File "/home/username/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/augur/__init__.py", line 12, in <module>
    from treetime import TreeTimeError, TreeTimeUnknownError
  File "/home/username/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/treetime/__init__.py", line 39, in <module>
    from .treetime import TreeTime, plot_vs_years
  File "/home/username/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/treetime/treetime.py", line 2, in <module>
    from scipy import optimize as sciopt
  File "/home/username/.local/lib/python3.10/site-packages/scipy/__init__.py", line 189, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/home/username/.nextstrain/runtimes/conda/env/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/username/.local/lib/python3.10/site-packages/scipy/optimize/__init__.py", line 430, in <module>
    from ._shgo import shgo
  File "/home/username/.local/lib/python3.10/site-packages/scipy/optimize/_shgo.py", line 10, in <module>
    from scipy import spatial
  File "/home/username/.local/lib/python3.10/site-packages/scipy/__init__.py", line 189, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/home/username/.nextstrain/runtimes/conda/env/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/username/.local/lib/python3.10/site-packages/scipy/spatial/__init__.py", line 116, in <module>
    from ._geometric_slerp import geometric_slerp
  File "/home/username/.local/lib/python3.10/site-packages/scipy/spatial/_geometric_slerp.py", line 9, in <module>
    from scipy.spatial.distance import euclidean
  File "/home/username/.local/lib/python3.10/site-packages/scipy/spatial/distance.py", line 121, in <module>
    from ..special import rel_entr
ImportError: cannot import name 'rel_entr' from 'scipy.special' (unknown location)
✔ yes: operating system is supported
✔ yes: runtime data dir doesn't have spaces
✔ yes: runtime appears set up
✔ yes: snakemake is installed and runnable
✘ no: augur is installed and runnable
✔ yes: auspice is installed and runnable

Checks failed!  Setup is unlikely to be fully functional.
```
Linux machinename 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tsibley** [comment]
@RubenHaag Sorry you're running into this bug. It's a leak in the isolation of our Conda runtime: the default Python user site directory (`~/.local/lib/python3.10/site-packages` here) is getting used (i.e. added to the module search path) by the Python installation in our runtime and the wrong `scipy` version is being found there.

I think we can fix this leak on our end. In the meantime, I expect you can work around this issue by setting `PYTHONNOUSERSITE=1` when invoking `nextstrain`, e.g.:

```
PYTHONNOUSERSITE=1 nextstrain setup --set-default conda
```

For the Nextstrain team, @corneliusroemer [flagged this issue in Slack](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1694713230463109) and I initially triaged it there.

**Comment by tsibley** [comment]
Potential fixes for [the Conda runner](https://github.com/nextstrain/cli/blob/master/nextstrain/cli/runner/conda.py):

1. Set [`PYTHONNOUSERSITE=1`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONNOUSERSITE) when entering the runtime, e.g. at

    https://github.com/nextstrain/cli/blob/3c93e87c2ac6bdd1b6a913070f709067b29a6cc1/nextstrain/cli/runner/conda.py#L139-L144

2. Set [`PYTHONUSERBASE`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUSERBASE) to a directory inside the runtime root, e.g.

    https://github.com/nextstrain/cli/blob/3c93e87c2ac6bdd1b6a913070f709067b29a6cc1/nextstrain/cli/runner/conda.py#L93

**Comment by tsibley** [comment]
(2) is probably the better option so that `PYTHONUSERBASE` from outside of the Conda env isn't another source of leaks.

Similarly, we should probably be plugging `PYTHONPATH` from outside as well?

A reproduction of the reported issue on my system:

```
$ NEXTSTRAIN_HOME=/tmp/nextstrain nextstrain setup conda
# works ok

$ NEXTSTRAIN_HOME=/tmp/nextstrain nextstrain check-setup conda
# still works ok

$ echo 'assert False, "Not the real scipy"' > ~/.local/lib/python3.10/site-packages/scipy.py

$ NEXTSTRAIN_HOME=/tmp/nextstrain nextstrain check-setup conda
nextstrain-cli is up to date!

Testing your setup…
Traceback (most recent call last):
  File "/tmp/nextstrain/runtimes/conda/env/bin/augur", line 6, in <module>
    from augur.__main__ import main
  File "/tmp/nextstrain/runtimes/conda/env/lib/python3.10/site-packages/augur/__init__.py", line 12, in <module>
    from treetime import TreeTimeError, TreeTimeUnknownError
  File "/tmp/nextstrain/runtimes/conda/env/lib/python3.10/site-packages/treetime/__init__.py", line 39, in <module>
    from .treetime import TreeTime, plot_vs_years
  File "/tmp/nextstrain/runtimes/conda/env/lib/python3.10/site-packages/treetime/treetime.py", line 2, in <module>
    from scipy import optimize as sciopt
  File "/home/tom/.local/lib/python3.10/site-packages/scipy.py", line 1, in <module>
    assert False, "Not the real scipy"
AssertionError: Not the real scipy

…
```

(but this is not the only way this leak can happen)

**Comment by RubenHaag** [comment]
So apparently I had a scipy installed outside of conda. Once I removed this and installed scipy in the conda enviroment everything worked fine
