### ISSUE TITLE
Catch exception when docker not installed

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/cli#33]
Running `nextstrain check-setup` without docker installed results in the following stack trace, which should be caught and something like "install docker" printed...

```
nextstrain-cli is up to date!

Testing your setup…
Traceback (most recent call last):
  File "/Users/naboo/miniconda3/envs/nextstrain-cli/bin/nextstrain", line 11, in <module>
    load_entry_point('nextstrain-cli', 'console_scripts', 'nextstrain')()
  File "/Users/naboo/github/nextstrain/cli/nextstrain/cli/__main__.py", line 10, in main
    return cli.run( argv[1:] )
  File "/Users/naboo/github/nextstrain/cli/nextstrain/cli/__init__.py", line 51, in run
    return opts.__command__.run(opts)
  File "/Users/naboo/github/nextstrain/cli/nextstrain/cli/command/check_setup.py", line 53, in run
    for runner in all_runners
  File "/Users/naboo/github/nextstrain/cli/nextstrain/cli/command/check_setup.py", line 53, in <listcomp>
    for runner in all_runners
  File "/Users/naboo/github/nextstrain/cli/nextstrain/cli/runner/docker.py", line 155, in test_setup
    *test_memory_limit()
  File "/Users/naboo/github/nextstrain/cli/nextstrain/cli/runner/docker.py", line 122, in test_memory_limit
    if image_exists():
  File "/Users/naboo/github/nextstrain/cli/nextstrain/cli/runner/docker.py", line 291, in image_exists
    stderr = subprocess.DEVNULL)
  File "/Users/naboo/miniconda3/envs/nextstrain-cli/lib/python3.7/subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/naboo/miniconda3/envs/nextstrain-cli/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/Users/naboo/miniconda3/envs/nextstrain-cli/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker'
```

**Comment by tsibley** [comment]
Ahh, feh. My intention was for this to work as you expect, but clearly it's not. Thanks for the catch!
