### ISSUE TITLE
Error during `nextstrain update conda`

### ISSUE THREAD

**Issue by victorlin** [nextstrain/cli#383]
_initially [reported](https://bedfordlab.slack.com/archives/C0K3GS3J8/p1722020639908189) on Slack_

Running `nextstrain update conda` resulted in an error:

```
Traceback (most recent call last):
 File "/Users/mparedes/.nextstrain/runtimes/conda/env/lib/python3.11/site-packages/snakemake/__init__.py", line 792, in snakemake
  success = workflow.execute(
       ^^^^^^^^^^^^^^^^^
 File "/Users/mparedes/.nextstrain/runtimes/conda/env/lib/python3.11/site-packages/snakemake/workflow.py", line 1246, in execute
  raise e
 File "/Users/mparedes/.nextstrain/runtimes/conda/env/lib/python3.11/site-packages/snakemake/workflow.py", line 1242, in execute
  success = self.scheduler.schedule()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/mparedes/.nextstrain/runtimes/conda/env/lib/python3.11/site-packages/snakemake/scheduler.py", line 617, in schedule
  run = self.job_selector(needrun)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/mparedes/.nextstrain/runtimes/conda/env/lib/python3.11/site-packages/snakemake/scheduler.py", line 758, in job_selector_ilp
  from stopit import ThreadingTimeout as Timeout, TimeoutException
 File "/Users/mparedes/.nextstrain/runtimes/conda/env/lib/python3.11/site-packages/stopit/__init__.py", line 10, in <module>
  import pkg_resources
 File "/Users/mparedes/.nextstrain/runtimes/conda/env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 95, in <module>
  from jaraco.text import (
 File "/Users/mparedes/.nextstrain/runtimes/conda/env/lib/python3.11/site-packages/setuptools/_vendor/jaraco/text/__init__.py", line 12, in <module>
  from jaraco.context import ExceptionTrap
 File "/Users/mparedes/.nextstrain/runtimes/conda/env/lib/python3.11/site-packages/setuptools/_vendor/jaraco/context.py", line 17, in <module>
  from backports import tarfile
ImportError: cannot import name 'tarfile' from 'backports' (/Users/mparedes/.nextstrain/runtimes/conda/env/lib/python3.11/site-packages/backports/__init__.py)
```

Unclear how to reproduce since we didn't grab the previous runtime version before applying the workaround.

This reportedly happened on an M1 and M2 Mac.

## Upstream issue

https://github.com/conda-forge/setuptools-feedstock/issues/351

## Workaround

`nextstrain setup conda --force` (from docs: [Managing an installation > Troubleshoot a broken installation > Conda](https://docs.nextstrain.org/en/latest/guides/manage-installation.html#troubleshoot-a-broken-installation))

## Possible solutions

1. Catch any errors from `nextstrain update conda` and suggest `nextstrain setup conda --force` as a workaround.

**Comment by victorlin** [comment]
Closing since the upstream issue has been closed. We can re-open if the error arises again – please add the output of `nextstrain version --verbose` if doing so!

**Comment by tsibley** [comment]
Reported by a user in https://discussion.nextstrain.org/t/nextstrain-installation/1757.
