### ISSUE TITLE
`nextstrain remote download s3://...` fails with ParamValidationError when URL is a directory 

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/cli#93]
**Current Behavior**  
`nextstrain remote download s3://...` fails when given a URL that is a directory and the recursive option (`-r/--recursively`) is not provided. 

**Expected behavior**  
The command probably should still fail, but I would like it to do so a little more gracefully, perhaps with a custom error message suggesting the user provide either a specific file path or the `-r` option if they intended to download the whole directory.

**How to reproduce**  
Steps to reproduce the current behavior:  
`nextstrain remote download s3://nextstrain-blab` produces the following error:

```sh
Traceback (most recent call last):
  File "/home/kairsten/.local/share/virtualenvs/cli-of_6ruDy/bin/nextstrain", line 11, in <module>
    load_entry_point('nextstrain-cli', 'console_scripts', 'nextstrain')()
  File "/home/kairsten/nextstrain/cli/nextstrain/cli/__main__.py", line 10, in main
    return cli.run( argv[1:] )
  File "/home/kairsten/nextstrain/cli/nextstrain/cli/__init__.py", line 35, in run
    return opts.__command__.run(opts)
  File "/home/kairsten/nextstrain/cli/nextstrain/cli/command/remote/download.py", line 73, in run
    for remote_file, local_file in downloads:
  File "/home/kairsten/nextstrain/cli/nextstrain/cli/remote/s3.py", line 71, in download
    assert_exists(object)
  File "/home/kairsten/nextstrain/cli/nextstrain/cli/remote/s3.py", line 170, in assert_exists
    if not exists(object):
  File "/home/kairsten/nextstrain/cli/nextstrain/cli/remote/s3.py", line 181, in exists
    object.load()
  File "/home/kairsten/.local/share/virtualenvs/cli-of_6ruDy/lib/python3.6/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/home/kairsten/.local/share/virtualenvs/cli-of_6ruDy/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/kairsten/.local/share/virtualenvs/cli-of_6ruDy/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/kairsten/.local/share/virtualenvs/cli-of_6ruDy/lib/python3.6/site-packages/botocore/client.py", line 608, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/kairsten/.local/share/virtualenvs/cli-of_6ruDy/lib/python3.6/site-packages/botocore/client.py", line 656, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/kairsten/.local/share/virtualenvs/cli-of_6ruDy/lib/python3.6/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter Key, value: 0, valid range: 1-inf
```

**Possible Solution**
We could take a page from a bash command like `cp`, and produce an error message along these lines:
For example, `cp some-existing-folder/ new-folder/` provides this output:
```sh
cp: -r not specified; omitting directory 'some-existing-folder/'
```
**Your environment: if running Nextstrain locally**  
ubuntu
nextstrain.cli 2.0.0.post1

**Comment by kairstenfay** [comment]
Oops! I created this issue with an incorrect title. I meant to reference `nextstrain remote download`, _not_ `nextstrain remote ls`.

**Comment by tsibley** [comment]
:+1: This would be a good usability fix.
